// GaiaHealth Metal Renderer — C FFI Header (auto-generated by cbindgen)
// Patents: USPTO 19/460,960 | USPTO 19/096,071 — © 2026 Richard Gillespie
// DO NOT EDIT — regenerate with: cbindgen --config cbindgen.toml --crate gaia-health-renderer --output gaia_health_renderer.h

#ifndef GAIA_HEALTH_RENDERER_H
#define GAIA_HEALTH_RENDERER_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Vertex stride in bytes (GxP regression-locked by RG-006).
#define GAIA_HEALTH_VERTEX_STRIDE 32

typedef void *GaiaHealthRendererHandle;

// Create a GaiaHealthRenderer. Returns opaque handle.
//
// # Safety
// Caller owns the handle. Must call `gaia_health_renderer_destroy` exactly once.
GaiaHealthRendererHandle gaia_health_renderer_create(void);

// Destroy a GaiaHealthRenderer.
//
// # Safety
// Handle must be valid, non-null, not yet destroyed.
void gaia_health_renderer_destroy(GaiaHealthRendererHandle handle);

// Set the current epistemic tag (0=M, 1=I, 2=A).
// The Metal shader reads this to switch between opaque / translucent / stippled rendering.
//
// # Safety
// Handle must be valid and non-null.
void gaia_health_renderer_set_epistemic(GaiaHealthRendererHandle handle, uint32_t tag);

// Read current epistemic tag.
//
// # Safety
// Handle must be valid and non-null.
uint32_t gaia_health_renderer_get_epistemic(GaiaHealthRendererHandle handle);

// Advance the MD frame counter.
//
// # Safety
// Handle must be valid and non-null.
void gaia_health_renderer_tick_frame(GaiaHealthRendererHandle handle);

// Read current MD frame count.
//
// # Safety
// Handle must be valid and non-null.
uint64_t gaia_health_renderer_get_frame_count(GaiaHealthRendererHandle handle);

#endif  /* GAIA_HEALTH_RENDERER_H */
