#!/usr/bin/env zsh
# GaiaFusion Operational Qualification (OQ)
# GFTCL-OQ-001 | GAMP 5 EU Annex 11 | FDA 21 CFR Part 11
# Run after iq_install.sh. Validates the build, tests, and cell configuration.
#
# Usage:  zsh scripts/oq_validate.sh
#
# Patents: USPTO 19/460,960 | USPTO 19/096,071 — © 2026 Richard Gillespie

set -euo pipefail

SCRIPT_DIR="${0:A:h}"
PROJECT_ROOT="${SCRIPT_DIR}/.."
EVIDENCE_DIR="${PROJECT_ROOT}/evidence/oq"
IDENTITY_DIR="${HOME}/.gaiaftcl"
IQ_RECEIPT="${PROJECT_ROOT}/evidence/iq/iq_receipt.json"
RECEIPT="${EVIDENCE_DIR}/oq_receipt.json"

mkdir -p "${EVIDENCE_DIR}"

# ── Colours ───────────────────────────────────────────────────────────────────
GRN=$'\033[0;32m'
RED=$'\033[0;31m'
YLW=$'\033[1;33m'
BLU=$'\033[0;34m'
BOLD=$'\033[1m'
NC=$'\033[0m'

typeset -i OQ_PASS=0
typeset -i OQ_FAIL=0
typeset -i OQ_WARN=0

pass() { print "${GRN}  ✅ PASS${NC}  $1"; (( OQ_PASS++ )) || true; }
fail() { print "${RED}  ❌ FAIL${NC}  $1"; (( OQ_FAIL++ )) || true; }
warn() { print "${YLW}  ⚠️  WARN${NC}  $1"; (( OQ_WARN++ )) || true; }
die()  { print "${RED}[OQ ABORT]${NC} $1" >&2; exit 1; }

print "${BOLD}${BLU}"
print "╔═══════════════════════════════════════════════════════════╗"
print "║  GaiaFusion Operational Qualification (GFTCL-OQ-001)    ║"
print "║  GAMP 5 / FDA 21 CFR Part 11                             ║"
print "╚═══════════════════════════════════════════════════════════╝${NC}"
print ""

# ── OQ-1: IQ Prerequisite ─────────────────────────────────────────────────────
print "${BOLD}OQ-1: IQ Prerequisites${NC}"

[[ -f "${IQ_RECEIPT}" ]] && pass "IQ receipt present: ${IQ_RECEIPT}" || \
    die "IQ receipt missing — run: zsh scripts/iq_install.sh first"

[[ -f "${IDENTITY_DIR}/cell_identity" ]] && pass "Cell identity present" || \
    die "Cell identity missing — run: zsh scripts/iq_install.sh first"

WALLET_MODE="$(stat -f "%Lp" "${IDENTITY_DIR}/wallet.key" 2>/dev/null || print "missing")"
if [[ "${WALLET_MODE}" == "600" ]]; then
    pass "Wallet key permissions: 600 (owner read-only)"
else
    fail "Wallet key permissions: ${WALLET_MODE} — must be 600"
fi

CELL_ID="$(python3 -c "import json; d=json.load(open('${IDENTITY_DIR}/cell_identity')); print(d['cell_id'])" 2>/dev/null || print "unknown")"
WALLET_ADDR="$(python3 -c "import json; d=json.load(open('${IDENTITY_DIR}/cell_identity')); print(d['wallet_address'])" 2>/dev/null || print "unknown")"
pass "Cell ID: ${CELL_ID:0:16}..."
pass "Wallet:  ${WALLET_ADDR}"

# ── OQ-2: Rust Metal Renderer Build ───────────────────────────────────────────
print "\n${BOLD}OQ-2: Rust Metal Renderer Build${NC}"

cd "${PROJECT_ROOT}/MetalRenderer/rust"

print "  Building debug..."
cargo build --target aarch64-apple-darwin 2>&1 | tail -3
pass "Rust debug build: OK"

print "  Building release..."
cargo build --release --target aarch64-apple-darwin 2>&1 | tail -3
pass "Rust release build: OK"

# Verify static library
LIB="${PROJECT_ROOT}/MetalRenderer/rust/target/aarch64-apple-darwin/release/libgaia_metal_renderer.a"
if [[ -f "${LIB}" ]]; then
    LIB_SIZE="$(du -h "${LIB}" | cut -f1)"
    pass "Static library: ${LIB} (${LIB_SIZE})"

    # Size check — must be < 5 MB (no OpenUSD bloat)
    LIB_BYTES="$(stat -f%z "${LIB}")"
    if (( LIB_BYTES < 5242880 )); then
        pass "Library size: ${LIB_SIZE} < 5 MB — zero-bloat confirmed"
    else
        fail "Library size: ${LIB_SIZE} exceeds 5 MB — check for OpenUSD contamination"
    fi
else
    fail "Static library not found: ${LIB}"
fi

# Copy to MetalRenderer/lib/
mkdir -p "${PROJECT_ROOT}/MetalRenderer/lib"
cp "${LIB}" "${PROJECT_ROOT}/MetalRenderer/lib/libgaia_metal_renderer.a"
pass "Library copied: MetalRenderer/lib/libgaia_metal_renderer.a"

# Verify C header generated by build.rs
HEADER="${PROJECT_ROOT}/MetalRenderer/include/gaia_metal_renderer.h"
if [[ -f "${HEADER}" ]]; then
    pass "C header: ${HEADER}"
    grep -q "gaia_metal_renderer_set_tau" "${HEADER}" && pass "Header contains: gaia_metal_renderer_set_tau" || fail "Header missing: gaia_metal_renderer_set_tau"
    grep -q "gaia_metal_renderer_get_tau" "${HEADER}" && pass "Header contains: gaia_metal_renderer_get_tau" || fail "Header missing: gaia_metal_renderer_get_tau"
else
    fail "C header missing: ${HEADER}"
fi

# ── OQ-3: Rust GxP Test Suite ─────────────────────────────────────────────────
print "\n${BOLD}OQ-3: Rust GxP Test Suite${NC}"

RUST_TEST_OUT="$(cargo test --target aarch64-apple-darwin 2>&1)"
print "${RUST_TEST_OUT}" | grep -E "test .* \.\.\." | head -30

RUST_PASS="$(print "${RUST_TEST_OUT}" | grep -E '^test result:' | awk '{sum += $4} END {print sum}')"
RUST_FAIL="$(print "${RUST_TEST_OUT}" | grep -E '^test result:' | awk '{sum += $6} END {print sum}')"

if [[ "${RUST_FAIL}" == "0" && -n "${RUST_PASS}" ]]; then
    pass "Rust tests: ${RUST_PASS} passed, 0 failed"
else
    fail "Rust tests: ${RUST_PASS} passed, ${RUST_FAIL} failed"
fi

# Minimum test count gate (14 unit tests in lib.rs)
if (( RUST_PASS >= 14 )); then
    pass "Rust test count: ${RUST_PASS} ≥ 14 (minimum)"
else
    fail "Rust test count: ${RUST_PASS} < 14 — tests may be missing"
fi

cd "${PROJECT_ROOT}"

# ── OQ-4: Swift Build ─────────────────────────────────────────────────────────
print "\n${BOLD}OQ-4: Swift Build${NC}"

SWIFT_BUILD_OUT="$(swift build 2>&1)"
if print "${SWIFT_BUILD_OUT}" | grep -qE "error:|Build FAILED"; then
    print "${SWIFT_BUILD_OUT}" | grep "error:" | head -10
    fail "Swift build failed"
else
    pass "Swift build: OK"
fi

# ── OQ-5: Swift Test Suite ────────────────────────────────────────────────────
print "\n${BOLD}OQ-5: Swift GxP Test Suite${NC}"

SWIFT_TEST_OUT="$(swift test 2>&1)" && SWIFT_OK=0 || SWIFT_OK=$?

SWIFT_PASS="$(print "${SWIFT_TEST_OUT}" | grep -cE "Test Case .* passed" || print 0)"
SWIFT_FAIL="$(print "${SWIFT_TEST_OUT}" | grep -cE "Test Case .* failed" || print 0)"

if [[ "${SWIFT_FAIL}" == "0" ]]; then
    pass "Swift tests: ${SWIFT_PASS} passed, 0 failed"
else
    print "${SWIFT_TEST_OUT}" | grep "FAILED" | head -10
    fail "Swift tests: ${SWIFT_PASS} passed, ${SWIFT_FAIL} failed"
fi

# ── OQ-6: τ Substrate Check ───────────────────────────────────────────────────
print "\n${BOLD}OQ-6: τ Substrate (Bitcoin Heartbeat)${NC}"

# NATS reachability
if nc -z -w2 localhost 4222 2>/dev/null; then
    pass "NATS: reachable on localhost:4222"
else
    warn "NATS: localhost:4222 unreachable — bitcoin τ sync not active (OK in dev)"
fi

# Bitcoin heartbeat service
if nc -z -w2 localhost 8850 2>/dev/null; then
    pass "Bitcoin heartbeat: reachable on localhost:8850"
    # Try to read current block height
    BH_JSON="$(curl -s --max-time 3 http://localhost:8850/heartbeat 2>/dev/null || print '{}')"
    BH="$(print "${BH_JSON}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('block_height','unknown'))" 2>/dev/null || print 'unknown')"
    pass "Current τ (block height): ${BH}"
else
    warn "Bitcoin heartbeat: localhost:8850 unreachable — TAU_NOT_IMPLEMENTED in renderer (OK in dev)"
fi

# Verify set_tau is wired in renderer source
grep -q "set_tau" "${PROJECT_ROOT}/MetalRenderer/rust/src/ffi.rs" && \
    pass "set_tau: wired in ffi.rs" || fail "set_tau: missing from ffi.rs"
grep -q "set_tau" "${PROJECT_ROOT}/MetalRenderer/rust/src/renderer.rs" && \
    pass "set_tau: implemented in renderer.rs" || fail "set_tau: missing from renderer.rs"
grep -q "setTau" "${PROJECT_ROOT}/GaiaFusion/MetalPlayback/RustMetalProxyRenderer.swift" && \
    pass "setTau: wired in RustMetalProxyRenderer.swift" || fail "setTau: missing from RustMetalProxyRenderer.swift"

# ── OQ-7: Git State ───────────────────────────────────────────────────────────
print "\n${BOLD}OQ-7: Git State${NC}"

GIT_BRANCH="$(git -C "${PROJECT_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || print 'unknown')"
GIT_COMMIT="$(git -C "${PROJECT_ROOT}" rev-parse HEAD 2>/dev/null || print 'unknown')"
pass "Branch: ${GIT_BRANCH}"
pass "Commit: ${GIT_COMMIT:0:12}..."

# Check for conflict markers
CONFLICTS="$(grep -rn "<<<<<<< \|>>>>>>> \|=======$" \
    "${PROJECT_ROOT}/GaiaFusion" "${PROJECT_ROOT}/MetalRenderer/rust/src" \
    --include="*.swift" --include="*.rs" 2>/dev/null | grep -v ".build" | head -5 || true)"
if [[ -z "${CONFLICTS}" ]]; then
    pass "No merge conflict markers in source"
else
    fail "Merge conflict markers found:\n${CONFLICTS}"
fi

# ── OQ-8: Write Receipt ───────────────────────────────────────────────────────
print "\n${BOLD}OQ-8: Writing OQ Receipt${NC}"

TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OQ_STATUS="$( [[ $OQ_FAIL -eq 0 ]] && print 'OQ_COMPLETE' || print 'OQ_FAILED' )"

cat > "${RECEIPT}" <<EOF
{
  "document_id": "GFTCL-OQ-001",
  "schema": "gaiaftcl_oq_receipt_v1",
  "timestamp": "${TIMESTAMP}",
  "git_commit": "${GIT_COMMIT}",
  "cell_id": "${CELL_ID}",
  "wallet_address": "${WALLET_ADDR}",
  "rust_tests_pass": ${RUST_PASS},
  "rust_tests_fail": ${RUST_FAIL},
  "swift_tests_pass": ${SWIFT_PASS},
  "swift_tests_fail": ${SWIFT_FAIL},
  "oq_pass": ${OQ_PASS},
  "oq_fail": ${OQ_FAIL},
  "oq_warn": ${OQ_WARN},
  "status": "${OQ_STATUS}",
  "next_step": "Run zsh scripts/run_full_pq_validation.sh"
}
EOF

pass "OQ receipt: ${RECEIPT}"

print ""
if [[ $OQ_FAIL -eq 0 ]]; then
    print "${GRN}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    print "${GRN}${BOLD}║  OPERATIONAL QUALIFICATION COMPLETE                      ║${NC}"
    print "${GRN}${BOLD}║  Rust: ${RUST_PASS} tests ✅  Swift: ${SWIFT_PASS} tests ✅${NC}"
    print "${GRN}${BOLD}║  OQ Score: ${OQ_PASS} checks passed, ${OQ_WARN} warnings      ║${NC}"
    print "${GRN}${BOLD}║  Next: zsh scripts/run_full_pq_validation.sh             ║${NC}"
    print "${GRN}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
else
    print "${RED}${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    print "${RED}${BOLD}║  OQ FAILED — ${OQ_FAIL} check(s) failed                  ║${NC}"
    print "${RED}${BOLD}║  Resolve failures above before running PQ                ║${NC}"
    print "${RED}${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    exit 1
fi
