#!/usr/bin/env bash
#
# Migrate Founder Wallet Address
#
# This script atomically updates all references to the old wallet address
# with the new wallet address generated by generate_founder_wallet.py
#
# SAFETY: Creates backups before modifying any files

set -euo pipefail

OLD_ADDRESS="0x858e7ED49680C38B0254abA515793EEc3d1989F5"
NEW_ADDRESS_FILE="/tmp/gaiaftcl_new_founder_address.txt"
BACKUP_DIR="/tmp/wallet_migration_backup_$(date +%Y%m%d_%H%M%S)"

echo "================================================================================"
echo "FOUNDER WALLET ADDRESS MIGRATION"
echo "================================================================================"
echo ""

# Check if new address file exists
if [ ! -f "$NEW_ADDRESS_FILE" ]; then
    echo "✗ New wallet address file not found: $NEW_ADDRESS_FILE"
    echo "   Run: python3 scripts/generate_founder_wallet.py"
    exit 1
fi

NEW_ADDRESS=$(cat "$NEW_ADDRESS_FILE")

# Validate new address format
if [[ ! "$NEW_ADDRESS" =~ ^0x[a-fA-F0-9]{40}$ ]]; then
    echo "✗ Invalid new wallet address format: $NEW_ADDRESS"
    exit 1
fi

echo "Old Address: $OLD_ADDRESS"
echo "New Address: $NEW_ADDRESS"
echo ""

# Create backup directory
mkdir -p "$BACKUP_DIR"
echo "✓ Created backup directory: $BACKUP_DIR"
echo ""

# Files to update
FILES_TO_UPDATE=(
    "./DEEP_DIVE_ARCHITECTURE_STATUS_2026_02_27.md"
    "./scripts/seed_founder_wallet_arangosh.sh"
)

# Backup and update each file
echo "Updating files..."
for file in "${FILES_TO_UPDATE[@]}"; do
    if [ ! -f "$file" ]; then
        echo "⚠️  File not found, skipping: $file"
        continue
    fi
    
    # Create backup
    cp "$file" "$BACKUP_DIR/$(basename $file)"
    echo "  ✓ Backed up: $file"
    
    # Check if file contains old address
    if grep -q "$OLD_ADDRESS" "$file"; then
        # Replace old address with new address
        if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS sed syntax
            sed -i '' "s/$OLD_ADDRESS/$NEW_ADDRESS/g" "$file"
        else
            # Linux sed syntax
            sed -i "s/$OLD_ADDRESS/$NEW_ADDRESS/g" "$file"
        fi
        echo "  ✓ Updated: $file"
    else
        echo "  ⚠️  No old address found in: $file"
    fi
done

echo ""
echo "================================================================================"
echo "MIGRATION COMPLETE"
echo "================================================================================"
echo ""
echo "Updated $(ls -1 "$BACKUP_DIR" | wc -l | tr -d ' ') files"
echo "Backups saved to: $BACKUP_DIR"
echo ""
echo "Next steps:"
echo "  1. Review changes: git diff"
echo "  2. Test the system"
echo "  3. Commit changes: git add -A && git commit -m 'Update founder wallet address'"
echo "  4. Deploy to cells: ./scripts/deploy_founder_wallet_system.sh"
echo ""
echo "To rollback:"
echo "  cp $BACKUP_DIR/* ."
echo ""
echo "================================================================================"
