// GaiaHealth MD Engine — C FFI Header (auto-generated by cbindgen)
// Patents: USPTO 19/460,960 | USPTO 19/096,071 — © 2026 Richard Gillespie
// DO NOT EDIT — regenerate with: cbindgen --config cbindgen.toml --crate biologit-md-engine --output gaia_health_engine.h

#ifndef GAIA_HEALTH_ENGINE_H
#define GAIA_HEALTH_ENGINE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque handle to BioState. GaiaHealth Swift stores as `UnsafeMutableRawPointer`.
typedef void *BioStateHandle;

// Create a new BioState. Returns opaque handle.
//
// # Safety
// Caller owns the handle. Must call `bio_state_destroy` exactly once.
BioStateHandle bio_state_create(void);

// Destroy a BioState. Frees heap memory and zeroes the Owl pubkey (zero-PII cleanup).
//
// # Safety
// `handle` must be a valid non-null pointer from `bio_state_create`, not yet destroyed.
void bio_state_destroy(BioStateHandle handle);

// Read current cell state discriminant (BiologicalCellState as u32).
//
// # Safety
// `handle` must be valid and non-null.
uint32_t bio_state_get_state(BioStateHandle handle);

// Read completed MD frame count.
//
// # Safety
// `handle` must be valid and non-null.
uint64_t bio_state_get_frame_count(BioStateHandle handle);

// Increment the MD frame counter. Called on each integration timestep.
//
// # Safety
// `handle` must be valid and non-null.
void bio_state_increment_frame(BioStateHandle handle);

// Read current epistemic tag (0=M, 1=I, 2=A).
//
// # Safety
// `handle` must be valid and non-null.
uint32_t bio_state_get_epistemic_tag(BioStateHandle handle);

// Transition cell state. Returns 1 if allowed, 0 if rejected by state machine.
//
// # Safety
// `handle` must be valid and non-null.
uint32_t bio_state_transition(BioStateHandle handle, uint32_t target_state);

// Moor an Owl identity. `pubkey_ptr` must point to a 66-char hex ASCII string.
// Returns 1 on success, 0 if the pubkey fails zero-PII validation.
//
// # Safety
// `handle` and `pubkey_ptr` must be valid and non-null. `pubkey_len` must match.
uint32_t bio_state_moor_owl(BioStateHandle handle, const uint8_t *pubkey_ptr, uintptr_t pubkey_len);

#endif  /* GAIA_HEALTH_ENGINE_H */
