name: "Xcode Cloud Prod Dispatch"

on:
  push:
    tags:
      - 'oq-*'
      - 'pq-*'
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Branch name or tag to trigger the workflow"
        required: true
        type: string
        default: "main"

permissions:
  contents: read

jobs:
  dispatch-xcode-cloud:
    name: Dispatch Xcode Cloud Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate App Store Connect JWT Token
        id: asc
        uses: yuki0n0/action-appstoreconnect-token@v1.0
        with:
          issuer id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          key id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}

      - name: Dispatch Xcode Cloud Workflow
        uses: yorifuji/actions-xcode-cloud-dispatcher@v1
        with:
          appstore-connect-token: ${{ steps.asc.outputs.token }}
          xcode-cloud-workflow-id: ${{ vars.XCODE_CLOUD_WORKFLOW_ID }}
          git-branch-name: ${{ github.event.inputs.branch-name || github.ref_name }}
